version: '3.3'

services:

    # Database Container
    development-db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: EAGLEEYE
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - 3306:3306
        # Schema is initialized here
        volumes:
            - ./development-db-data:/var/lib/mysql
            - ./development-db-init/schema.sql:/docker-entrypoint-initdb.d/initdb.sql
    
    # Eagle Eye container for testing 
    test-eagle-service:
        build: ./test-eagle
        volumes:
            - ./test-eagle:/user/src/app
        ports:
            - 5004:80
        network_mode: host
        depends_on:
            - development-db
    
    development-eagle-service:
        build: ./development-eagle
        container_name: development_eagle
        command: tail -f /dev/null
        volumes:
            - ./development-eagle:/usr/src/app
            - /Users/kennethlund/Desktop:/usr/src/app/output
        ports:
            - 5005:80
        network_mode: host
        depends_on:
            - development-db

    # This container creates a simple API for our test website to present data
    test-website-backend:
        build: ./test-website-backend
        volumes:
            - ./test-website-backend:/user/src/app
        ports:
            - 5001:80
        depends_on:
            - development-db

    # Apache hosted test website for scraping
    test-website-frontend1:
            image: php:apache
            volumes:
                - ./test-website-containers/test-website-frontend1:/var/www/html
            ports:
                - 5000:80
            depends_on:
                - test-website-backend
    
    test-website-frontend2:
            image: php:apache
            volumes:
                - ./test-website-containers/test-website-frontend2:/var/www/html
            ports:
                - 5002:80
            depends_on:
                - test-website-backend
    
    test-website-frontend3:
            image: php:apache
            volumes:
                - ./test-website-containers/test-website-frontend3:/var/www/html
            ports:
                - 5003:80
            depends_on:
                - test-website-backend

    

    

    
